name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "*"
  pull_request:
    branches: ["main"]

env:
  PYTHONFAULTHANDLER: "true"
  MATURIN_VERSION: "1.3.1"

jobs:
  tests:
    name: "${{ matrix.os }}: Python ${{ matrix.python-version }}"
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Set up virtual environment
        run: python -m venv venv

      - name: Activate virtual environment (Unix)
        if: runner.os != 'Windows'
        run: |
          source venv/bin/activate
          echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV

      - name: Activate virtual environment (Windows)
        if: runner.os == 'Windows'
        run: |
          .\venv\Scripts\Activate
          echo "VIRTUAL_ENV=$(pwd)\venv" | Out-String | Set-Content -Path $env:GITHUB_ENV -Encoding utf8

      - name: Install dependencies and build the package (Windows)
        if: runner.os == 'Windows'
        run: |
          pip install --upgrade pip
          pip install pillow maturin==${{ env.MATURIN_VERSION }} pytest
          New-Item -ItemType Directory -Force -Path target/wheels
          python -m maturin build --release --out target/wheels
          $WHEEL_FILE = (Get-ChildItem target/wheels/*.whl).FullName
          python -m pip install $WHEEL_FILE
          python -m pip list  # List all installed packages to debug
        shell: pwsh

      - name: Install dependencies and build the package
        run: |
          pip install --upgrade pip
          pip install pillow maturin==${{ env.MATURIN_VERSION }} pytest
          python -m maturin build --release --out target/wheels
          WHEEL_FILE=$(ls target/wheels/*.whl)
          python -m pip install $WHEEL_FILE
          python -m pip list  # List all installed packages to debug
        shell: bash
        if: runner.os != 'Windows'

      - name: Run tests
        run: python -m pytest

  build-and-publish:
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Set up virtual environment
        run: python -m venv venv
      - name: Activate virtual environment
        run: |
          source venv/bin/activate
          echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
      - name: Install maturin
        run: |
          pip install --upgrade pip
          pip install maturin
      - name: Build wheels with maturin
        run: python -m maturin build --release --out target/wheels

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels/*.whl
      - name: Publish to PyPI with maturin
        run: maturin publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
