name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "*"
  pull_request:
    branches: ["main"]

env:
  PYTHONFAULTHANDLER: "true"
  MATURIN_VERSION: "1.3.1" # Updated to match your pyproject.toml

jobs:
  tests:
    name: "${{ matrix.os }}: Python ${{ matrix.python-version }}"
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"] # Updated to reflect your supported versions
        os: ["ubuntu-latest", "macos-latest", "windows-latest"] # Updated OS versions

    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install maturin
        run: pip install maturin==${{ env.MATURIN_VERSION }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and install the package
        run: maturin develop
      - name: Run tests
        run: pytest

  build-and-publish:
    needs: tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install maturin
        run: pip install maturin==${{ env.MATURIN_VERSION }}
      - name: Build wheels and sdist
        run: maturin publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
